### ISSUE TITLE
Set up controllers and routes for authentication

### ISSUE THREAD

**Issue by emilsharier** [emilsharier/playlist-backend-v2#3]
**Task list**
- [x] Controller for authentication
- [x] Route for authentication
- [x] Entities for user (for the middleware to work)

**Comment by emilsharier** [comment]
Closed with branch ```issue#3``` ✅
